### ISSUE TITLE
Want to know where the SLS is located

### ISSUE THREAD

**Issue by Futschel** [netizen539/civcraft#33]
Dear netizen, first of all thanks for this nice plugIn collection / creation !

i have configred the SLS and have an working heartbeat, can u tell me on which website the Server get listed ? Just to check if the setting i made are show correctly ;-)

regards from germany
Futschel

**Comment by ataranlen** [comment]
The SLS site went down a long time ago, it was hosted on the civcraft.net domain, but as that has transferred hands a few times, they didn't keep the service running.

**Comment by Futschel** [comment]
To Sad ... okay so i can also turn off the hearbeat ;-)

please keep me posted if it went up anytime again.
